## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './C:\Users\znk67\OneDrive\桌面\Part01/'

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 4-5: truncated \UXXXXXXXX escape (<ipython-input-2-a35083a0a043>, line 2)

In [3]:
app_train = pd.read_csv("application_train.csv")

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [4]:
app_train.shape

(307511, 122)

#### 列出所有欄位

In [14]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
app_train.iloc[0,:]

SK_ID_CURR                                             100002
TARGET                                                      1
NAME_CONTRACT_TYPE                                 Cash loans
CODE_GENDER                                                 M
FLAG_OWN_CAR                                                N
FLAG_OWN_REALTY                                             Y
CNT_CHILDREN                                                0
AMT_INCOME_TOTAL                                       202500
AMT_CREDIT                                             406598
AMT_ANNUITY                                           24700.5
AMT_GOODS_PRICE                                        351000
NAME_TYPE_SUITE                                 Unaccompanied
NAME_INCOME_TYPE                                      Working
NAME_EDUCATION_TYPE             Secondary / secondary special
NAME_FAMILY_STATUS                       Single / not married
NAME_HOUSING_TYPE                           House / apartment
REGION_POPULATION_RELATIVE                           0.018801
DAYS_BIRTH                                              -9461
DAYS_EMPLOYED                                            -637
DAYS_REGISTRATION                                       -3648
DAYS_ID_PUBLISH                                         -2120
OWN_CAR_AGE                                               NaN
FLAG_MOBIL                                                  1
FLAG_EMP_PHONE                                              1
FLAG_WORK_PHONE                                             0
FLAG_CONT_MOBILE                                            1
FLAG_PHONE                                                  1
FLAG_EMAIL                                                  0
OCCUPATION_TYPE                                      Laborers
CNT_FAM_MEMBERS                                             1
REGION_RATING_CLIENT                                        2
REGION_RATING_CLIENT_W_CITY                                 2
WEEKDAY_APPR_PROCESS_START                          WEDNESDAY
HOUR_APPR_PROCESS_START                                    10
REG_REGION_NOT_LIVE_REGION                                  0
REG_REGION_NOT_WORK_REGION                                  0
LIVE_REGION_NOT_WORK_REGION                                 0
REG_CITY_NOT_LIVE_CITY                                      0
REG_CITY_NOT_WORK_CITY                                      0
LIVE_CITY_NOT_WORK_CITY                                     0
ORGANIZATION_TYPE                      Business Entity Type 3
EXT_SOURCE_1                                         0.083037
EXT_SOURCE_2                                         0.262949
EXT_SOURCE_3                                         0.139376
APARTMENTS_AVG                                         0.0247
BASEMENTAREA_AVG                                       0.0369
YEARS_BEGINEXPLUATATION_AVG                            0.9722
YEARS_BUILD_AVG                                        0.6192
COMMONAREA_AVG                                         0.0143
ELEVATORS_AVG                                               0
ENTRANCES_AVG                                           0.069
FLOORSMAX_AVG                                          0.0833
FLOORSMIN_AVG                                           0.125
LANDAREA_AVG                                           0.0369
LIVINGAPARTMENTS_AVG                                   0.0202
LIVINGAREA_AVG                                          0.019
NONLIVINGAPARTMENTS_AVG                                     0
NONLIVINGAREA_AVG                                           0
APARTMENTS_MODE                                        0.0252
BASEMENTAREA_MODE                                      0.0383
YEARS_BEGINEXPLUATATION_MODE                           0.9722
YEARS_BUILD_MODE                                       0.6341
COMMONAREA_MODE                                        0.0144
ELEVATORS_MODE                                              0
ENTRANCES_MODE                                          0.069
FLOORSMAX_MODE                                         0.0833
FLOORSMIN_MODE                                          0.125
LANDAREA_MODE                                          0.0377
LIVINGAPARTMENTS_MODE                                   0.022
LIVINGAREA_MODE                                        0.0198
NONLIVINGAPARTMENTS_MODE                                    0
NONLIVINGAREA_MODE                                          0
APARTMENTS_MEDI                                         0.025
BASEMENTAREA_MEDI                                      0.0369
YEARS_BEGINEXPLUATATION_MEDI                           0.9722
YEARS_BUILD_MEDI                                       0.6243
COMMONAREA_MEDI                                        0.0144
ELEVATORS_MEDI                                              0
ENTRANCES_MEDI                                          0.069
FLOORSMAX_MEDI                                         0.0833
FLOORSMIN_MEDI                                          0.125
LANDAREA_MEDI                                          0.0375
LIVINGAPARTMENTS_MEDI                                  0.0205
LIVINGAREA_MEDI                                        0.0193
NONLIVINGAPARTMENTS_MEDI                                    0
NONLIVINGAREA_MEDI                                          0
FONDKAPREMONT_MODE                           reg oper account
HOUSETYPE_MODE                                 block of flats
TOTALAREA_MODE                                         0.0149
WALLSMATERIAL_MODE                               Stone, brick
EMERGENCYSTATE_MODE                                        No
OBS_30_CNT_SOCIAL_CIRCLE                                    2
DEF_30_CNT_SOCIAL_CIRCLE                                    2
OBS_60_CNT_SOCIAL_CIRCLE                                    2
DEF_60_CNT_SOCIAL_CIRCLE                                    2
DAYS_LAST_PHONE_CHANGE                                  -1134
FLAG_DOCUMENT_2                                             0
FLAG_DOCUMENT_3                                             1
FLAG_DOCUMENT_4                                             0
FLAG_DOCUMENT_5                                             0
FLAG_DOCUMENT_6                                             0
FLAG_DOCUMENT_7                                             0
FLAG_DOCUMENT_8                                             0
FLAG_DOCUMENT_9                                             0
FLAG_DOCUMENT_10                                            0
FLAG_DOCUMENT_11                                            0
FLAG_DOCUMENT_12                                            0
FLAG_DOCUMENT_13                                            0
FLAG_DOCUMENT_14                                            0
FLAG_DOCUMENT_15                                            0
FLAG_DOCUMENT_16                                            0
FLAG_DOCUMENT_17                                            0
FLAG_DOCUMENT_18                                            0
FLAG_DOCUMENT_19                                            0
FLAG_DOCUMENT_20                                            0
FLAG_DOCUMENT_21                                            0
AMT_REQ_CREDIT_BUREAU_HOUR                                  0
AMT_REQ_CREDIT_BUREAU_DAY                                   0
AMT_REQ_CREDIT_BUREAU_WEEK                                  0
AMT_REQ_CREDIT_BUREAU_MON                                   0
AMT_REQ_CREDIT_BUREAU_QRT                                   0
AMT_REQ_CREDIT_BUREAU_YEAR                                  1
Name: 0, dtype: object

#### 截取部分資料

In [10]:
app_train.iloc[0:3,:]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子